### ISSUE TITLE
1.2.* supporting for new mod versions?

### ISSUE THREAD

**Issue by byaka** [Real-Gecko/KSP-BonVoyage#8]
Unfortenly KSP 1.3 not ready yet for RSS+RO, so i'm steal use 1.2 version.
But latest versions of your awesome mod craching my game on loading due 'localizator' class issue.
Any chance to solving this problem?

**Comment by jarosm** [comment]
Latest version of BonVoyage compatible with KSP 1.2.2 is 0.12 ( [https://github.com/Real-Gecko/KSP-BonVoyage/releases/tag/0.12.0](url) )

Higher versions are not meant to be backward compatible. If they work with older versions of KSP, good for you, but don't expect backward compatibility from any mod, because a lot can be changed between KSP versions.
